config/routes.rb
Dougie::Application.routes.draw do

  resources :authentications

  
  devise_for :users, :timeout_in => 7.days,
    :controllers => {:registrations => 'registrations'}

  get "tag/index" # ???
  match "/explore" => "tags#index" #** public **#

  match "/documents/create/:tag_id" => "documents#create"
  resources :documents, :only => [:edit, :update, :destroy]

  match "/review/:id" => "documents#review" #** public **#
  match "/review/dir/:id" => "tags#review" #** public **#
  match "/mems/update/:id/:confidence/:importance" => "mems#update"
  resources :lines, :only => [:update]
  
  resources :tags, :only => [:destroy, :create, :update]
  match "/tags/json" => "tags#json"

  match "users/welcome" => "users#home"
  root :to => "users#home"

  match '/auth/:provider/callback' => 'authentications#create'
  match '/users/get_email' => 'users#get_email'
  resources :authentications

  match "users/simple_sign_in" => "users#simple_sign_in"

  Dougie::Application.routes.draw do |map|
    map.connect ':action', :controller => "static"
  end

end

app/views/shared/_authentication.html.erb
<% if user_signed_in? %>
    <a href="/" style="float:left;"><img src="/images/logos/zendo_slogan_small.png" /></a>
    <span style="float:right; margin: 8px 6px 0 0;">
            Welcome, <%= current_user.first_name %>&nbsp;|&nbsp;
            <%= link_to "Edit Account", edit_user_registration_path %>&nbsp;|&nbsp;
            <%= link_to "Sign Out", destroy_user_session_path %>
    </span>

<% elsif ['static'].count(controller.controller_name) > 0 %>
    <a href="/"><img src="/images/logos/zendo_slogan_small.png" /></a>
<% else %>
    <a href="/"><img src="/images/logos/zendo_beta.png" /></a>
<% end %>

app/views/shared/_authentication.mobile.erb
<% if user_signed_in? %>
    <a href="/" style="float:left;"><img src="/images/logos/zendo_slogan_small.png" /></a>
    <span style="margin: 8px 6px 0 0;">
            Welcome, <%= current_user.first_name %>&nbsp;|&nbsp;
            <%= link_to "Edit Account", edit_user_registration_path %>&nbsp;|&nbsp;
            <%= link_to "Sign Out", destroy_user_session_path %>
    </span>

<% elsif ['static'].count(controller.controller_name) > 0 %>
    <a href="/"><img src="/images/logos/zendo_slogan_small.png" /></a>
<% else %>
    <a href="/"><img src="/images/logos/zendo_beta.png" /></a>
<% end %>

app/views/shared/_sign_up_form.html.erb
<div id="sign_up_inline">
  <div class="restrictions">

    <p><strong>Sign up through one of these services:</strong></p>

    <!--<a href="/auth/twitter" class="auth_provider">
      <%#= image_tag "logos/twitter_32.png", :size => "32x32", :alt => "Twitter" %>
    </a>
    <a href="/auth/open_id" class="auth_provider">
      <%#= image_tag "logos/openid_32.png", :size => "32x32", :alt => "OpenID" %>
    </a>-->
    <a href="/auth/facebook" class="auth_provider">
      <%= image_tag "logos/facebook_32.png", :size => "32x32", :alt => "Facebook" %>
    </a>
    <a href="/auth/open_id?openid_url=gmail.com" class="auth_provider">
      <%= image_tag "logos/google_32.png", :size => "32x32", :alt => "Google" %>
    </a>

    <div class="clr"></div>

    <strong>We're beta! So far we support:</strong>
    <ul>
      <li>Firefox 3</li>
      <li>Chrome</li>
      <li>Safari 5</li>
      <li>Opera 11</li>
      <li>IE 8</li>
    </ul>
  </div>

  <div class="form_container">
    <h2>Sign up!</h2>
    
    <%= error_messages_for @resource %>
    <%#<div class="error_messages"><h2>Invalid Fields</h2><p>Correct the following errors and try again.</p><ul><li>Email has already been taken</li></ul></div>%>

    <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
      <%= devise_error_messages! rescue "" %>

      <p><%= f.label :first_name %><br />
      <%= f.text_field :first_name %></p>

      <p><%= f.label :last_name %><br />
      <%= f.text_field :last_name %></p>

      <p><%= f.label :email %><br />
      <%= f.text_field :email %></p>

      <p><%= f.label :password %><br />
      <%= f.password_field :password %></p>

      <p><%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %></p

      <p><%= f.submit "Sign up" %></p>
    <% end %>

    <%= link_to "Didn't receive confirmation link?", new_confirmation_path(resource_name) %><br />
    <a href="/users/password/new">Reset password?</a>

  </div>

  <div class="clr"></div>
</div>

app/views/shared/_sign_up_form.mobile.erb
<div id="sign_up_inline">
  <div class="restrictions">

    <p><strong>Sign up through one of these services:</strong></p>

    <!--<a href="/auth/twitter" class="auth_provider">
      <%#= image_tag "logos/twitter_32.png", :size => "32x32", :alt => "Twitter" %>
    </a>
    <a href="/auth/open_id" class="auth_provider">
      <%#= image_tag "logos/openid_32.png", :size => "32x32", :alt => "OpenID" %>
    </a>-->
    <a href="/auth/facebook" class="auth_provider">
      <%= image_tag "logos/facebook_32.png", :size => "32x32", :alt => "Facebook" %>
    </a>
    <a href="/auth/open_id?openid_url=gmail.com" class="auth_provider">
      <%= image_tag "logos/google_32.png", :size => "32x32", :alt => "Google" %>
    </a>

    <div class="clr"></div>

    <strong>We're beta! So far we support:</strong>
    <ul>
      <li>Firefox 3</li>
      <li>Chrome</li>
      <li>Safari 5</li>
      <li>Opera 11</li>
      <li>IE 8</li>
    </ul>
  </div>

  <div class="form_container">
    <h2>Sign up!</h2>

    <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
      <%= devise_error_messages! rescue "" %>

      <p><%= f.label :first_name %><br />
      <%= f.text_field :first_name %></p>

      <p><%= f.label :last_name %><br />
      <%= f.text_field :last_name %></p>

      <p><%= f.label :email %><br />
      <%= f.text_field :email %></p>

      <p><%= f.label :password %><br />
      <%= f.password_field :password %></p>

      <p><%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %></p

      <p><%= f.submit "Sign up" %></p>
    <% end %>

    <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
    <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
    <a href="/users/password/new">Reset password?</a>

  </div>

  <div class="clr"></div>
</div>